### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by tigerclawn82** [Wisembly/basil.js#32]
I want to use [Sourcegraph](https://sourcegraph.com) for basil.js code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/Wisembly/basil.js. (It should only take 30 seconds.)

Thank you!

**Comment by matghaleb** [comment]
@tigerclawn82, is it ok for you ?

**Comment by tigerclawn82** [comment]
yeah, thanks :-)
