### ISSUE TITLE
Please release 0.4.2 to npm

### ISSUE THREAD

**Issue by aaronjensen** [Wisembly/basil.js#34]
Thanks for merging https://github.com/Wisembly/basil.js/pull/30, it looks like a release to npm didn't happen though, could you please do that when you get a chance @guillaumepotier or @matghaleb Thanks!

**Comment by guillaumepotier** [comment]
Right this is done now.

Just to know because I'm curious, why using npm rather than bower for basil?

Best

**Comment by aaronjensen** [comment]
Bower has pretty much fallen out of use in modern projects due to webpack/browserify. We still have a few dependencies in bower and we're in the process of porting them all over to npm. No need to have two package managers and npm is superior to bower due to its dependency management.

**Comment by guillaumepotier** [comment]
ok good to know ;) thx!

Best

**Comment by aaronjensen** [comment]
np, thank you!
