### ISSUE TITLE
escaping keys caused namespaced cookie names to change

### ISSUE THREAD

**Issue by aaronjensen** [Wisembly/basil.js#35]
This isn't a problem for us because our site isn't live yet, but I just wanted you all to be aware that #30 changed the name of namespaced cookies because the `:` gets escaped to `%3A`. 

You might consider changing the namespace separator to `.` as that won't get escaped. It'd still be a breaking change though. The other option would be to escape the namespace and the key separately, which would leave the `:` in there, which may or may be valid in all browsers--it's hard to tell from the rfc what is actually valid in a cookie name.

**Comment by guillaumepotier** [comment]
Hi @aaronjensen this is a good point.

I think it is safer to have this BC and be compliant with RFC. I'll add a notice.

**Comment by matghaleb** [comment]
@aaronjensen we just released https://github.com/Wisembly/basil.js/releases/tag/0.4.3 using `.` separator instead of `:`

**Comment by aaronjensen** [comment]
Great, thanks for the heads up.

**Comment by aaronjensen** [comment]
@matghaleb @guillaumepotier would you mind releasing on npm please? Thanks!

**Comment by guillaumepotier** [comment]
Right!

Should be done by now.

Best
