### ISSUE TITLE
Using with react

### ISSUE THREAD

**Issue by markwain** [Wisembly/basil.js#43]
Apparently this library conflicts with some internal react process due to its globally defined context. 

If connecting this library and using an undefined variable in some of the React components I get error like this:
`Warning: Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onMountComponent() to fire for the child before its parent includes it in onSetChildren().
Invariant Violation: Expected onMountComponent() to fire for the child before its parent includes it in onSetChildren().`
The normal error is something like `foo is not defined` with file and location on the right side. But instead I get an very strange error from react's warning.js file that leads me to nowhere.

**Comment by markwain** [comment]
Sorry guys ... just found out that my assumption were wrong. Sorry.

**Comment by rrrodzilla** [comment]
What was the issue?

**Comment by happysuns** [comment]
I was in the componentWillMount hook that appeared in this error how do you solve it。
