### ISSUE TITLE
Delimiter is not configurable

### ISSUE THREAD

**Issue by codeburke** [Wisembly/basil.js#48]
Our project has been using 0.4.1 for quite a while. We attempted to update to 0.4.4 (latest) and ran into the breaking `:` to `.` key delimiter change [(#35)](https://github.com/Wisembly/basil.js/issues/35) .

Instead of hardcoding a delimiter I propose that we expose `keyDelimiter` as a Basil.option.

**Comment by codeburke** [comment]
I've submitted https://github.com/Wisembly/basil.js/pull/47 as a proposed solution.

**Comment by guillaumepotier** [comment]
Merged and released in `0.4.5`

Thanks again

**Comment by codeburke** [comment]
Thanks! I'm not seeing 0.4.5 on npm yet, can you confirm it was published?

**Comment by guillaumepotier** [comment]
[Should be good by now](https://www.npmjs.com/package/basil.js)

**Comment by codeburke** [comment]
Yep, I see it. Thanks for the quick turnaround!

On Tue, Jun 13, 2017 at 10:55 AM, Guillaume Potier <notifications@github.com
