### ISSUE TITLE
SameSite property on cookies not supported

### ISSUE THREAD

**Issue by mikejwis** [Wisembly/basil.js#59]
It looks like basil does not support use of the SameSite property.  Is basil still being maintained and do you plan on adding support for SameSite?  I'm happy to submit a PR for this if you'd like.

**Comment by guillaumepotier** [comment]
Hi there,

Thanks for your issue. Basil is still being maintained and used on many projects.

Indeed, feel free to submit a PR for this, I'll happily review it in order to merge it soon.

Best

**Comment by mikejwis** [comment]
New version looks great.  Thanks!
